---
- hosts: 172.31.15.139
  become: yes
  tasks:
   - name: i want to execute  direct linux command
     command: hostname -f
     register: myresult

   - name: i want to  display first task result
     debug: 
        msg: "{{myresult}}"


   - name: i want install git 
     apt:
       name: git
       state: present

   - name: i want install tree
     apt: 
       name: tree
       state: present
     when: myresult.stderr !=""