---
- hosts: 172.31.15.139
  become: yes
  tasks:
  - name: install git
    apt: 
         name: git
         stateee: present
    ignore_errors: yes

  - name: install tree
    apt: 
      name: tree
      state: present

  - name: wget
    apt:
      name: wget
      state: present
   