---
- hosts: all
  become: yes
  tasks:
  
    - name: i want to install webserver
      apt:
        name: "{{mywebpackonubuntu}}"
        state: present   
      when: ansible_os_family =="Debian"      